#
# (C) Copyright 2015
# Texas Instruments Incorporated - http://www.ti.com/
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_REMOTEPROC) += rproc-uclass.o

# Remote proc drivers - Please keep this list alphabetically sorted.
obj-$(CONFIG_K3_SYSTEM_CONTROLLER) += k3_system_controller.o
obj-$(CONFIG_REMOTEPROC_K3) += k3_rproc.o
obj-$(CONFIG_REMOTEPROC_SANDBOX) += sandbox_testproc.o
obj-$(CONFIG_REMOTEPROC_TI_POWER) += ti_power_proc.o
obj-$(CONFIG_TI_SCI_PROC_CONTROL) += ti_sci_proc_control.o
